from . import hr_employee
from . import hr_ngach_cong_chuc
from . import hr_contract
from . import hr_position_history
from . import hr_study_process
from . import hr_political_organizations
from . import hr_label
from . import hr_bonus
from . import hr_discipline
from . import hr_family_relationship
from . import hr_salary_process
from . import hr_position_history
from . import hr_employee_report
from . import hr_job
from . import current_address
from . import res_users
from . import payroll_plan
from . import payroll_report
from . import training_plan
from . import training_report
from . import hr_instruction
from . import discipline_report